set(CTEST_PROJECT_NAME "SimpleITK")
set(CTEST_NIGHTLY_START_TIME "1:00:00 UTC")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "www.cdash.org")
set(CTEST_DROP_LOCATION "/CDash/submit.php?project=SimpleITK")
set(CTEST_DROP_SITE_CDASH TRUE)
