#!/usr/bin/env bash
#=============================================================================
# Copyright 2010-2012 Kitware, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#=============================================================================


die() {
	echo 'pre-commit hook failure' 1>&2
	echo '-----------------------' 1>&2
	echo '' 1>&2
	echo "$@" 1>&2
	exit 1
}

#-----------------------------------------------------------------------------
# Check for committer identity.
advice='
Use the commands

	git config --global user.name '\''Your Name'\''
	git config --global user.email '\''you@yourdomain.com'\''

to introduce yourself to Git before committing.'


if test -z "$CI";then

  # Ensure name and email are available.
  git var GIT_AUTHOR_IDENT > /dev/null ||
  die 'Identity not configured!' "$advice"

  # Validate the name and email.
  git var GIT_AUTHOR_IDENT | cut -d "<" -f1 | sed 's,\s$,,' | grep ' '  > /dev/null ||
  die 'Set user.name to your Real Name (with a space), not a userid.' "$advice"
  git var GIT_AUTHOR_IDENT | cut -d ">" -f1 | cut -d "<" -f2 | grep '^[^@]*@[^@]*$' > /dev/null ||
  die 'Set user.email to an email address (userid@validdomain.com).' "$advice"
fi

#-----------------------------------------------------------------------------
# Check content that will be added by this commit.

if git rev-parse --verify -q HEAD > /dev/null; then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Disallow non-ascii file names.  The printable range starts at the
# space character and ends with tilde.
if test "$(git diff --cached --name-only --diff-filter=A -z $against |
	   LC_ALL=C tr -d '[ -~]\0')"; then
	die 'Non-ascii file names may not be added:
'"$(git diff --cached --name-only --diff-filter=A $against)"
fi

#-----------------------------------------------------------------------------
# Builtin whitespace checks.
bad=$(git diff-index --check --cached $against --) || die "$bad"

# Approximate whitespace=tab-in-indent check with Git < 1.7.2.
git --version | grep -q " \(1\.[0-6]\|1\.7\.[01]\)" &&
approx_tab_in_indent=true || approx_tab_in_indent=false
check_tab() {
	lines=$(git diff-index -p --cached $against -- "$1" |
	        grep '^+	') &&
	echo "$lines" |
	while read line; do
		echo "$1: tab in indent." &&
		echo "$line"
	done
}

# Reject addition of a line without a newline at end-of-file.
check_no_lf_at_eof() {
	lines=$(git diff-index -p --cached $against -- "$1" | tail -2)
	if echo "$lines" | head -1 | grep -q '^+' &&
	   echo "$lines" | tail -1 | grep -q '^\\ No newline'; then
		echo "$1: No newline at end of file"
	fi
}

# Custom whitespace checks.
check_whitespace() {
	ws=$(git check-attr whitespace -- "$file" |
	     sed 's/^[^:]*: whitespace: //')
	if $approx_tab_in_indent; then
		case ",$ws," in
			*,tab-in-indent,*) check_tab "$1" ;;
		esac
	fi
	case ",$ws," in
		*,no-lf-at-eof,*) check_no_lf_at_eof "$1" ;;
	esac
}
bad=$(git diff-index --name-only --cached $against -- |
while read file; do
	check_whitespace "$file"
done)
test -z "$bad" || die "$bad"
