## File containing manual fixes for code generated by swig
## that is wrong.
## This file will get shorter and disappear as we improve swig.

PermuteAxesImageFilter_DefaultOrder =
function(value, .copy = FALSE)
{
  PermuteAxesImageFilter_DefaultOrder_get(.copy)
}
