FROM quay.io/pypa/manylinux2014_x86_64
LABEL maintainer="Insight Software Consortium <community@itk.org>"

WORKDIR /tmp/

RUN yum update -y\
    && yum -y install mono-devel java-devel ninja-build\
     && yum clean all

# User is expected to mount directory to "/work"
ENTRYPOINT ["bash", "-c", "/work/io/imagefiles/cmd.sh" ]
