FROM quay.io/pypa/manylinux2014_aarch64
LABEL maintainer="Insight Software Consortium <community@itk.org>"

WORKDIR /tmp/
RUN yum update -y\
    && yum -y install java-devel\
    && yum clean all


# User is expected to mount directory to "/work"
ENTRYPOINT ["bash", "-c", "/work/io/imagefiles/cmd.sh" ]
