FROM quay.io/pypa/manylinux2014_aarch64
MAINTAINER Insight Software Consortium <community@itk.org>

WORKDIR /tmp/

RUN yum -y install java-devel

# User is expected to mount directory to "/work"
ENTRYPOINT ["bash", "-c", "/work/io/imagefiles/cmd.sh" ]
