FROM quay.io/pypa/manylinux1_x86_64
MAINTAINER Insight Software Consortium <community@itk.org>

ADD https://cmake.org/files/v3.13/cmake-3.13.5.tar.gz \
    https://www.openssl.org/source/old/1.0.2/openssl-1.0.2u.tar.gz \
    /tmp/

WORKDIR /tmp/
COPY ./imagefiles/install.sh ./
RUN bash -v install.sh && rm -rf /tmp/*

# User is expected to mount directory to "/work"
ENTRYPOINT ["bash", "-c", "/work/io/imagefiles/cmd.sh" ]
