FROM quay.io/pypa/manylinux2014_x86_64
MAINTAINER Insight Software Consortium <community@itk.org>

WORKDIR /tmp/

# User is expected to mount directory to "/work"
ENTRYPOINT ["bash", "-c", "/work/io/imagefiles/cmd.sh" ]
