FROM quay.io/pypa/manylinux2010_x86_64
MAINTAINER Insight Software Consortium <community@itk.org>

WORKDIR /tmp/

RUN yum -y install mono-devel java-devel

# User is expected to mount directory to "/work"
ENTRYPOINT ["bash", "-c", "/work/io/imagefiles/cmd.sh" ]
