#ifndef __SimpleITK_h
#define __SimpleITK_h

#include <stdint.h>

#include "sitkDetail.h"
#include "sitkMacro.h"
#include "sitkImage.h"

#include "sitkImageHashFilter.h"
#include "sitkRecursiveGaussianImageFilter.h"
#include "sitkPixelIDTypeLists.h"
#include "sitkImageFileReader.h"
#include "sitkImageFileWriter.h"
#include "sitkStatisticsImageFilter.h"

// These headers are auto-generated
#include "sitkAcosImageFilter.h"
#include "sitkAddImageFilter.h"
#include "sitkAndImageFilter.h"
#include "sitkAsinImageFilter.h"
#include "sitkAtanImageFilter.h"
#include "sitkAtan2ImageFilter.h"
#include "sitkBinaryMagnitudeImageFilter.h"
#include "sitkBinaryThresholdImageFilter.h"
#include "sitkCosImageFilter.h"
#include "sitkCurvatureFlowImageFilter.h"
#include "sitkDivideImageFilter.h"
#include "sitkExpImageFilter.h"
#include "sitkExpNegativeImageFilter.h"
#include "sitkIntensityWindowingImageFilter.h"
#include "sitkInvertIntensityImageFilter.h"
#include "sitkLogImageFilter.h"
#include "sitkLog10ImageFilter.h"
#include "sitkMaskImageFilter.h"
#include "sitkMaskNegatedImageFilter.h"
#include "sitkMaximumImageFilter.h"
#include "sitkMinimumImageFilter.h"
#include "sitkMultiplyImageFilter.h"
#include "sitkNotImageFilter.h"
#include "sitkOrImageFilter.h"
#include "sitkRescaleIntensityImageFilter.h"
#include "sitkSigmoidImageFilter.h"
#include "sitkSinImageFilter.h"
#include "sitkSqrtImageFilter.h"
#include "sitkSquareImageFilter.h"
#include "sitkSquaredDifferenceImageFilter.h"
#include "sitkSubtractImageFilter.h"
#include "sitkTanImageFilter.h"
#include "sitkXorImageFilter.h"
#endif
