set(SITK_CMAKE_MINIMUM_REQUIRED_VERSION "3.16.3")
set(SITK_CMAKE_POLICY_VERSION "3.16.3")

if("${CMAKE_VERSION}" VERSION_LESS_EQUAL "${SITK_CMAKE_POLICY_VERSION}")
  set(SITK_CMAKE_POLICY_VERSION "${CMAKE_VERSION}")
endif()
